name: Packagist Sync

on:
  release:
    types: [ released ]

jobs:
  sync:
    name: Sync Packagist
    runs-on: ubuntu-latest
    steps:
      - name: Sync Packagist
        uses: hotaruma/packagist-sync@v1.0.1
        with:
          api-token: ${{ secrets.PACKAGIST_TOKEN }}

